version: "3.9"
services:
  build:
    image: emscripten/emsdk
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: "emcc compute-cpp.cpp -o build/compute-cpp.html --std=c++11 -s \"EXPORTED_FUNCTIONS=['_square']\""