version: "3.9"
services:
  build:
    image: fvbakel/kotlin-native
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: bash -c "kotlinc-native compute-kt.kt -target wasm32 -o build/compute-kt && sed -i 's/let instance/var instance/' build/compute-kt.wasm.js"